feat: Add run() wrapper with command output assertions
Add a new test pattern for asserting command outputs and exit status
through a run() wrapper function and corresponding assertion functions.

Addresses issue: https://github.com/bash-unit/bash_unit/issues/134
--------------------------------------
User story suggested pipe syntax:
  command_under_test | should_display "${expected_pattern}"
  command_under_test | err_should_contain "${expected_pattern}"

Implemented wrapper pattern:
  run command_under_test && assert_run_output_matches "${expected_pattern}"
  run command_under_test && assert_run_error_matches "${expected_pattern}"

Works also as separate lines:
  run command_under_test
  assert_run_output_matches "${expected_pattern}"
  assert_run_error_matches "${expected_pattern}"

The wrapper pattern achieves the same readability while providing more
flexibility and reliability.

Problem with pipes:
- pipes carry only stdout
- harder to resolve exit status if needed
- can't verify multiple conditions independently

Usage Examples
--------------
Simple one-liners:
  run my_script && assert_run_success
  run my_command && assert_run_output_equals "expected"
  run failing_cmd && assert_run_status_code 42

Multiple assertions:
  run my_script.sh input.txt
  assert_run_success
  assert_run_output_matches "^Processed.*successfully"
  assert_run_error_equals ""

diff --git a/bash_unit b/bash_unit
--- a/bash_unit
+++ b/bash_unit
@@ -17,6 +17,7 @@
 #  https://github.com/bash-unit/bash_unit
 
 # shellcheck disable=2317  # Ignore unreachable - most function are not called.
+# shellcheck disable=2329  # Ignore unreachable - most function are not called.
 # shellcheck disable=2155  # Ignore Declare and assign separately
 # spellchecker: ignore NOCOLOR SHUF
 
@@ -191,6 +192,101 @@ assert_no_diff() {
 
   assert "diff '${expected}' '${actual}'"  \
     "$message expected '${actual}' to be identical to '${expected}' but was different"
+}
+
+#
+# Run command wrapper with output assertions
+#
+
+BASH_UNIT_RUN_STATUS=""
+BASH_UNIT_RUN_OUTPUT=""
+BASH_UNIT_RUN_ERROR=""
+
+run() {
+  BASH_UNIT_RUN_STATUS=""
+  BASH_UNIT_RUN_OUTPUT=""
+  BASH_UNIT_RUN_ERROR=""
+
+  local stdout=$(mktemp)
+  local stderr=$(mktemp)
+  # shellcheck disable=2064
+  trap "$RM -f \"$stdout\" \"$stderr\"" EXIT
+
+  BASH_UNIT_RUN_STATUS=0
+  "$@" >"$stdout" 2>"$stderr" || BASH_UNIT_RUN_STATUS=$?
+  BASH_UNIT_RUN_OUTPUT=$("$CAT" "$stdout")
+  BASH_UNIT_RUN_ERROR=$("$CAT" "$stderr")
+
+  "$RM" -f "$stdout" "$stderr"
+  trap - EXIT
+}
+
+assert_run_success() {
+  local message=${1:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [ "$BASH_UNIT_RUN_STATUS" != 0 ]; then
+    fail "${message}expected run command to succeed but status was $BASH_UNIT_RUN_STATUS"
+  fi
+}
+
+assert_run_fails() {
+  local message=${1:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [ "$BASH_UNIT_RUN_STATUS" == 0 ]; then
+    fail "${message}expected run command to fail but status was 0"
+  fi
+}
+
+assert_run_status_code() {
+  local expected=$1
+  local message=${2:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [ "$BASH_UNIT_RUN_STATUS" != "$expected" ]; then
+    fail "${message}expected run command to have status code $expected but was $BASH_UNIT_RUN_STATUS"
+  fi
+}
+
+assert_run_output_equals() {
+  local expected=$1
+  local message=${2:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [ "$expected" != "$BASH_UNIT_RUN_OUTPUT" ]; then
+    fail "${message}expected run output [$expected] but was [$BASH_UNIT_RUN_OUTPUT]"
+  fi
+}
+
+assert_run_output_matches() {
+  local pattern=$1
+  local message=${2:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [[ ! "$BASH_UNIT_RUN_OUTPUT" =~ $pattern ]]; then
+    fail "${message}expected run output to match regex [$pattern] but was [$BASH_UNIT_RUN_OUTPUT]"
+  fi
+}
+
+assert_run_error_equals() {
+  local expected=$1
+  local message=${2:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [ "$expected" != "$BASH_UNIT_RUN_ERROR" ]; then
+    fail "${message}expected run error [$expected] but was [$BASH_UNIT_RUN_ERROR]"
+  fi
+}
+
+assert_run_error_matches() {
+  local pattern=$1
+  local message=${2:-}
+  [[ -z $message ]] || message="$message\n"
+
+  if [[ ! "$BASH_UNIT_RUN_ERROR" =~ $pattern ]]; then
+    fail "${message}expected run error to match regex [$pattern] but was [$BASH_UNIT_RUN_ERROR]"
+  fi
 }
 
 fake() {
